import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<div className="home">
			<Head>
				<title>Hulu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>HULU is about to get down</h1>
			</main>
		</div>
	);
}
